/** Canonical values stored in the family profile, with their translation keys. */
export const NAKSHATRAS = [
  { value: 'Ashwini', key: 'nakshatra.ashwini' },
  { value: 'Bharani', key: 'nakshatra.bharani' },
  { value: 'Krittika', key: 'nakshatra.krittika' },
  { value: 'Rohini', key: 'nakshatra.rohini' },
  { value: 'Mrigashira', key: 'nakshatra.mrigashira' },
  { value: 'Ardra', key: 'nakshatra.ardra' },
  { value: 'Punarvasu', key: 'nakshatra.punarvasu' },
  { value: 'Pushya', key: 'nakshatra.pushya' },
  { value: 'Ashlesha', key: 'nakshatra.ashlesha' },
  { value: 'Magha', key: 'nakshatra.magha' },
  { value: 'Purva Phalguni', key: 'nakshatra.purvaPhalguni' },
  { value: 'Uttara Phalguni', key: 'nakshatra.uttaraPhalguni' },
  { value: 'Hasta', key: 'nakshatra.hasta' },
  { value: 'Chitra', key: 'nakshatra.chitra' },
  { value: 'Swati', key: 'nakshatra.swati' },
  { value: 'Vishakha', key: 'nakshatra.vishakha' },
  { value: 'Anuradha', key: 'nakshatra.anuradha' },
  { value: 'Jyeshtha', key: 'nakshatra.jyeshtha' },
  { value: 'Mula', key: 'nakshatra.mula' },
  { value: 'Purva Ashadha', key: 'nakshatra.purvaAshadha' },
  { value: 'Uttara Ashadha', key: 'nakshatra.uttaraAshadha' },
  { value: 'Shravana', key: 'nakshatra.shravana' },
  { value: 'Dhanishta', key: 'nakshatra.dhanishta' },
  { value: 'Shatabhisha', key: 'nakshatra.shatabhisha' },
  { value: 'Purva Bhadrapada', key: 'nakshatra.purvaBhadrapada' },
  { value: 'Uttara Bhadrapada', key: 'nakshatra.uttaraBhadrapada' },
  { value: 'Revati', key: 'nakshatra.revati' },
] as const;

export const RASHIS = [
  { value: 'Mesh', key: 'rashi.mesh' },
  { value: 'Vrishabh', key: 'rashi.vrishabh' },
  { value: 'Mithun', key: 'rashi.mithun' },
  { value: 'Kark', key: 'rashi.kark' },
  { value: 'Simha', key: 'rashi.simha' },
  { value: 'Kanya', key: 'rashi.kanya' },
  { value: 'Tula', key: 'rashi.tula' },
  { value: 'Vrishchik', key: 'rashi.vrishchik' },
  { value: 'Dhanu', key: 'rashi.dhanu' },
  { value: 'Makar', key: 'rashi.makar' },
  { value: 'Kumbh', key: 'rashi.kumbh' },
  { value: 'Meen', key: 'rashi.meen' },
] as const;

/** Suggestions for the free-text relation field. */
export const RELATION_KEYS = [
  'relation.self',
  'relation.wife',
  'relation.husband',
  'relation.son',
  'relation.daughter',
  'relation.father',
  'relation.mother',
  'relation.grandfather',
  'relation.grandmother',
  'relation.brother',
  'relation.sister',
  'relation.daughterInLaw',
  'relation.grandson',
  'relation.granddaughter',
] as const;
